mysite/blog/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url, include
from django.views.generic import TemplateView
from blog.views import (start_page,
                        article_list,
                        articles_list_update,
                        article_create,
                        article_update,
                        article_delete,
                        article_detail,
                        add_like,
                        photo)


app_name = 'blog'


urlpatterns = [
    # url(r'^mine/$', MyView.as_view(), name='my-view'),

    # include urls_api
    url(r'^api/', include('blog.class_based.urls')),

    url(r'^$', start_page, name='start_page'),

    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/list/$', article_list, name='article_list'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/list/update/$', articles_list_update,
        name='articles_list_update'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/create/$', article_create, name='article_create'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/edit/$', article_update,
        name='article_update'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/delete/$', article_delete,
        name='article_delete'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/$', article_detail,
        name='article_detail'),
    url(r'^(?P<item_slug>.*)/list/$', photo, name='photo'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact_page.html')),
    url(r'^add_like/(?P<id>[0-9]+)/$', add_like, name='add_like'),
    ]

mysite/templates/base.html
{% load staticfiles %} {% load i18n %}{% load my_filters %}{% load navigation_tags %}{% load humanize %}
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8" name="keywords" content="3d Max,django,python,Поліщук Михайло">

    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %} {% trans 'Поліщук Михайло' %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <script type="text/javascript" src="{% static 'js/jquery-2.1.4.js' %}"></script>

    {% block style %}{% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="{% static 'js/html5shiv.min.js' %}"></script>
      <script src="{% static 'js/respond.min.js' %}"></script>
      <script src="{% static 'js/angular.js' %}"></script>
    <![endif]-->

    {% block scripts %}{% endblock scripts %}

</head>

<body>
{% block error %}

    {% block create_article_form %}

        {% block login %}

            <!-- Header -->
            <header class="container" role="banner">

                {% include 'messages.html' %}

                <div class="row">
                    <div class="col-lg-8 col-xs-12 col-lg-offset-1">
                        <h2><a href="/">{% trans 'Поліщук Михайло Віталійович' %}</a></h2>
                    </div>

                    {% include 'languages.html' %}

                </div>

                {% include 'user_login.html' %}

            </header>

            {% block breadcrumbs %}

                {% navigation_menu path=request.path %}

            {% endblock %}

            <!-- Wrapper -->
            <main class="wrapper" role="main">
                <div class="container">

                    {% block content_title %}

                    {% endblock %}

                    {% block content %}

                    {% endblock %}

                </div>

                {% include 'footer.html' %}

            </main>

        {% endblock login %}

    {% endblock create_article_form %}

{% endblock error %}

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
{#<script src="{% static 'js/jquery.min.js' %}"></script>#}
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

mysite/templates/content_start_page.html
{% extends "base.html" %}{% load staticfiles %} {% load i18n %}


{% block title %}{% endblock %}


{% block style %}


{% endblock %}


{% block content %}

    <!-- Content -->
    <div class="col-lg-12 jumbotron">
        <h1>Сайт-представлення!</h1>
        <p>Даний сайт розроблений для представлення моїх навиків в програмуванні
            мовою Python та його фреймворком Django, а також показати, що я за особистість, чим цікавлюся і займаюся.
            При розробці була використана бібліотека JQuery. В майбутньому даний сайт буде реалізований за допомогою Django Rest та AngularJS </p>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-5 col-xs-6 jumbotron">
        <form id="form-massage" action="{% url 'blog:start_page' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                {{ field.errors }}
                {{ field }}
            {% endfor %}
            <button type="submit" class="btn btn-primary">відправити повідомлення</button>
        </form>
    </div>
    {% if users %}
        <div class="col-lg-7 col-md-6 col-sm-6 col-xs-5 pull-right jumbotron">
        <div>
            <h1 id="list-users" class="text-center">Зареєстровані користувачі</h1>
        </div>
        <div class="row">
            {% for user in users %}
                <div id="people" class="col-lg-2 col-sm-4 col-xs-6 text-center">
                    <img src="{{ user.avatar.url }}" class="img-circle" width="70px" height="70px">
                    <h5>{{ user.user.username }}</h5>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% if users.has_other_pages %}
    <div id="pagination" class="row pg-users">
        <ul class="pagination pagination-sm">
            {% if users.has_previous %}
                <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><a href="">&laquo;</a></li>
            {% endif %}
            {% for page in users.paginator.page_range %}
                {% if page == users.number %}
                    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                {% else %}
                    <li><a href="?page={{ page }}">{{ page }}</a></li>
                {% endif%}
            {% endfor %}
            {% if users.has_next %}
                <li><a href="?page={{ users.next_page_number }}">&raquo</a></li>
            {% else %}
                <li class="disabled"><a href="">&raquo</a></li>
            {% endif %}
        </ul>
    </div>
{% endif %}
</div>

{% endblock %}

mysite/templates/footer.html
{% load staticfiles %} {% load i18n %}

<!-- Footer -->
<footer class="footer">
    <div class="container">
        <div  class="row">
            <div class="col-lg-4 col-md-5 col-sm-5 text-center">
                <h4>Особистий сайт Поліщука Михайла</h4>
            </div>
            <div class="col-lg-5 col-md-5 col-sm-4 text-center">
                <h4>Я в соцмережах:</h4>
            </div>
            <div class="col-lg-3 col-md-2 col-sm-3 text-center">
                <h4>2016 MySite</h4>
            </div>
        </div>
    </div>
</footer>

mysite/templates/messages.html
{% if messages %}
        {% for message in messages%}
            <div class="messages form-group has-{{ message.extra_tags }}">
                <label class="control-label">
                    <p><em>{{ message }}</em></p>
                </label>
            </div>
        {% endfor %}
{% endif %}