mysite/blog/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url, include
from django.views.generic import TemplateView
from blog.views import (start_page,
                        article_list,
                        articles_list_update,
                        article_create,
                        article_update,
                        article_delete,
                        article_detail,
                        add_like,
                        photo)


app_name = 'blog'


urlpatterns = [
    # url(r'^mine/$', MyView.as_view(), name='my-view'),

    # include urls_api
    url(r'^api/', include('blog.class_based.urls')),

    url(r'^$', start_page, name='start_page'),

    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/list/$', article_list, name='article_list'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/list/update/$', articles_list_update,
        name='articles_list_update'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/create/$', article_create, name='article_create'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/edit/$', article_update,
        name='article_update'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/delete/$', article_delete,
        name='article_delete'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/$', article_detail,
        name='article_detail'),
    url(r'^(?P<item_slug>.*)/list/$', photo, name='photo'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact_page.html')),
    url(r'^add_like/(?P<id>[0-9]+)/$', add_like, name='add_like'),
    ]

mysite/loginsys/urls.py
from django.conf.urls import url
from loginsys.views import (login,
                            logout,
                            register,
                            update,
                            delete,
                            # show_users
)
from django.contrib.auth import views as auth_views

app_name = 'loginsys'

urlpatterns = [
    # it`s for action in admin
    # url(r'^(?P<ct>[0-9]+)/(?P<ids>.*)/$', show_users, name='show_users'),

    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'password_reset_form.html',
                                                          'email_template_name': 'password_reset_email.html',
                                                          'subject_template_name': 'password_reset_subject.txt',
                                                          'post_reset_redirect': 'loginsys:password_reset_done'},
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'password_reset_done.html',
                                                                    'current_app': 'loginsys'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,
        {'template_name': 'password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^update/$', update, name='update'),
    url(r'^(?P<id>[0-9]+)/delete/$', delete, name='delete'),
    ]

mysite/loginsys/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import  get_user_model

from django.conf import settings

from django.utils.translation import ugettext_lazy as _
import os

from django.core.files import File

def upload_location(instance, filename):
    path = 'upload/profile_images'
    profile = Profile.objects.order_by("user_id").last()
    if instance.user_id is not None:
        return os.path.join(path, str(instance.user_id), str(filename))
    if not profile:
        return os.path.join(path, 'FIRST_Profile', str(filename))
    if profile.user_id is not None:
        new_id = profile.user_id + 1
        return os.path.join(path, str(new_id), str(filename))


class ProfileManager(models.Manager):

    # def get_by_natural_key(self, first_name, last_name):
    #     return self.get(user__first_name=first_name, user__last_name=last_name)

    def get_by_natural_key(self, first_name, last_name):
        profile = self.get(user__first_name=first_name, user__last_name=last_name)
        return profile.user.get_full_name()


class Profile(models.Model):
    objects = ProfileManager()

    class Meta:
        db_table = "profile"
        verbose_name = _("Профіль користувача")
        verbose_name_plural = _("Профілі користувачів")

    # user = models.OneToOneField(User, primary_key=True, related_name="profile", verbose_name=_("Користувач"),
    #                             on_delete=models.CASCADE)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, primary_key=True, related_name="profile", verbose_name=_("Користувач"),
                                on_delete=models.CASCADE, unique=True)
    sex = models.CharField(max_length=20, choices=(('Man', _('Чоловік')), ('Woman', _('Жінка'))),
                           verbose_name=_("Стать"))
    avatar = models.ImageField(verbose_name=_("Аватарка"), upload_to=upload_location, blank=True,
                               help_text=_("Фото користувача"))
    profile_create = models.DateTimeField(auto_now_add=True, verbose_name=_("Дата створення профіля"))
    profile_update = models.DateTimeField(auto_now=True, verbose_name=_("Дата оновлення профіля"))
    date_of_birth = models.DateField(blank=True, null=True, verbose_name=_("Дата народження"))

    def __str__(self):
        return self.user.get_full_name()

    def natural_key(self):                 # natural key for serialization also for serialization for manage.py dumpdata --natural-foreign
        return self.user.get_full_name()

mysite/loginsys/views.py
from django.shortcuts import render_to_response, redirect, render, get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.contrib import auth
from django.core.context_processors import csrf
from loginsys.models import Profile
from loginsys.form import (ProfileCreationForm,
                           ProfileUpdateForm)
from django.contrib import messages
from django.conf import settings
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User


def login(request):
    args = {}
    args.update(csrf(request))
    path = request.META.get('HTTP_REFERER', '/')
    if 'next' in request.GET:
        return_path = request.GET['my_redirect_field']
    elif path == request.build_absolute_uri():
        return_path = '/'
    else:
        return_path = path
    args['return_path'] = return_path
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            last_login = user.last_login.strftime("%d-%m-%Y %H:%M:%S")
            auth.login(request, user)
            messages.success(request, _('Вітаю Вас на сайті, ' + username + '! Останій раз на сайті Ви були ' +
                                        str(last_login) + '.'), extra_tags='success')
            return redirect(return_path)
        elif not username and password:
            args['login_error_username'] = "Обов'язково введіть ім'я!"
            return render_to_response('login.html', args)
        elif username and not password:
            args['username'] = username
            args['login_error_password'] = "Обов'язково введіть пароль!"
            return render_to_response('login.html', args)
        elif not username and not password:
            args['login_error_username_password'] = "Ви не ввели жодних даних!"
            return render_to_response('login.html', args)
        else:
            args['login_error'] = 'Користувач не знайдений!'
            return render_to_response('login.html', args)
    else:
        args['username'] = ''
        args['password'] = ''
    return render(request, 'login.html', args)


def logout(request):
    messages.success(request, 'Щастливо, ' + request.user.username + '!', extra_tags='success')
    auth.logout(request)
    return_path = request.META.get('HTTP_REFERER', '/')  # HTTP_REFERER — ссылка на страницу с которой пришли на текущую, если такая существует
    return redirect(return_path)


def register(request):
    title = 'Форма для реєстрації'
    button_create = 'Зареєструватися'
    path = request.META.get('HTTP_REFERER', '/')
    if path == request.build_absolute_uri():
        return_path = '/'
    else:
        return_path = path
    form = ProfileCreationForm()
    if request.POST:
        form = ProfileCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            new_user = auth.authenticate(username=form.cleaned_data['username'],
                                         password=form.cleaned_data['password2'])
            new_profile = Profile(user=new_user, avatar=form.cleaned_data['avatar'],
                                  sex=form.cleaned_data['sex'])
            new_profile.save()
            auth.login(request, new_user)
            messages.success(request, 'Дякую, що долучилися до нас, ' + new_profile.user.username + '!',
                             extra_tags='success')
            return redirect(return_path)
        else:
            form = form
    context = {
        'title': title,
        'button_create': button_create,
        'form': form,
        'return_path': return_path,
        }
    return render(request, 'register.html', context)


def update(request):
    path = request.META.get('HTTP_REFERER', '/')
    if path == request.build_absolute_uri():
        return_path = '/'
    else:
        return_path = path
    instance = get_object_or_404(User, username=request.user)
    form = ProfileUpdateForm(request.POST or None, request.FILES or None, instance=instance,
                             initial={'sex': instance.profile.sex, 'avatar': instance.profile.avatar})
    if form.is_valid():
        form.save()
        update_session_auth_hash(request, form.instance)
        messages.success(request, _('Ви змінили свій профіль, ' + instance.username + '!'),
                         extra_tags='success')
        return redirect(return_path)
    else:
        form = form
    title = _('Форма для зміни профіля \'' + str(instance.get_full_name() + '\''))
    button_update = _('Змінити')
    button_delete = _('Видалити')
    context = {
        'title': title,
        'button_create': button_update,
        'button_delete': button_delete,
        'form': form,
        'return_path': return_path,
        'profile': instance,
        }
    return render(request, 'register.html', context)


def delete(request, id=None):
    instance = get_object_or_404(User, id=id)
    name = instance.get_full_name()
    return_path = settings.LOGIN_REDIRECT_URL
    title = _('Ви впевнені, що хочете видалити профіль \'' + name + '\' ?')
    button_delete = _('видалити профіль')
    button_cancel = _('відміна')
    context = {
        'title': title,
        'button_delete': button_delete,
        'button_cancel': button_cancel,
        'return_path': return_path,
        }
    if request.POST:
        instance.delete()
        messages.success(request, _('Користувач \'' + name + '\' видалений!'), extra_tags='success')
        return redirect(return_path)
    return render(request, 'profile_delete_form.html', context)


# from django.contrib.contenttypes.models import ContentType
#
#
# def show_users(request, ct, ids):
#     model = get_object_or_404(ContentType, id=ct)
#     queryset = model.get_all_objects_for_this_type()
#     users = []
#     users_ids = ids.split(',')
#     if len(users_ids) > 1:
#         for user_id in users_ids:
#             content = queryset.get(pk=user_id)
#             users.append(content)
#     else:
#         users = queryset.get(pk=ids)
#     return render(request, 'show_user_from_admin.html', {'users': users})

mysite/loginsys/templates/login.html
{% extends 'base.html'%} {% load i18n %} {% load staticfiles %}


{% block login %}

            <div id="login-register" class="col-md-4 col-sm-6 col-xs-10 col-md-offset-4 col-sm-offset-3 col-xs-offset-1">
                <form action="" method="post">
                    {% csrf_token %}
                    <label for="username">І'мя користувача</label>
                    <input  value="{{username}}" type="text" class="form-control" name="username"
                            id="username" placeholder="введіть ім'я користувача" >
                    <div class="form-group has-error">
                        {% if login_error_username %}
                            <label class="control-label errorlist"><em>{{login_error_username}}</em></label>
                        {% endif %}
                    </div>
                    <label for="password">Пароль</label>
                    <input type="password" class="form-control" name="password" id="password" placeholder="пароль">
                    <div class="form-group has-error">
                        {% if login_error_password %}
                            <label class="control-label"><em>{{login_error_password}}</em></label>
                        {% endif %}
                    </div>
                    <div class="form-group has-error">
                        {% if login_error_username_password %}
                            <label class="control-label"><em>{{login_error_username_password}}</em></label>
                        {% elif login_error%}
                            <label class="control-label"><em>{{login_error}}</em></label>
                        {% endif %}
                    </div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary">Увійти</button>
                        <button type="button" class="btn btn-default pull-right"><a href="{{ return_path }}">Відміна</a></button>
                        <button type="button" class="btn btn-default"><a href="{% url 'loginsys:password_reset' %}">{% trans 'Забули пароль?' %}</a></button>
                    </div>
                </form>
            </div>

{% endblock %}

mysite/loginsys/templates/profile_delete_form.html
{% extends "base.html" %} {% load staticfiles %} {% load i18n %}


{% block title%}{{title}}{% endblock title%}

{% block style %}

{% endblock style %}

{% block login %}

<div class="col-sm-3 col-sm-offset-4">
    <h4 class="danger">{{title}}</h4>
    <form  method="POST" action="">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="{{button_delete}}"/>
        <a class="btn btn-default pull-right" href="{{ return_path }}">{{ button_cancel }}</a>
    </form>
</div>

{% endblock %}

mysite/loginsys/templates/register.html
{% extends "base.html" %} {% load staticfiles %} {% load i18n %}

{% block title%}{{title}}{% endblock title%}

{% block scripts %}

    {{ form.media }}

{% endblock scripts %}

{% block login %}

    {% get_current_language as LANGUAGE_CODE %}
    <p id="lang_cod" hidden="hidden">{{ LANGUAGE_CODE }}</p>

    <div id="login-register" class="col-md-4 col-md-offset-4">
        <h3>{{title}}</h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="btn btn-primary" type="submit" >{{ button_create }}</button>
            {% if button_delete %}
                <button class="btn btn-danger"><a href="{% url 'loginsys:delete' id=request.user.id %}">{{ button_delete }}</a></button>
            {% endif %}
            <button class="btn btn-default pull-right"><a href="{{ return_path }}">Відміна</a></button>
        </form>
    </div>

{% endblock %}

mysite/loginsys/templates/show_user_from_admin.html
{% extends "base.html" %}{% load staticfiles %}


{% block content %}
    <div class="row">
        <div class="container">
            {% if users|length > 1 %}
                {% for user in users %}
                    <div class="col-md-4">
                    <div class="well">
                        <h3>{{ user }}</h3>
                        <p><strong>Стать:</strong> {{ user.get_sex_display }};</p>
                        <p><strong>Дата реєстрації:</strong> {{ user.user.date_joined }};</p>
                        <p><strong>Email:</strong> {{ user.user.email }}</p>
                        <p><strong>Адміністратор:</strong> {{ user.user.is_superuser }};</p>
                        <p><strong>Дата останього входу:</strong> {{ user.user.last_login }};</p>
                        <p><strong>Аватар:</strong> {{ user.avatar.url}}.</p>
                    </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-md-4 well">
                    <h3>{{ users }}</h3>
                    <p><strong>Стать:</strong> {{ users.get_sex_display }};</p>
                    <p><strong>Дата реєстрації:</strong> {{ users.user.date_joined }};</p>
                    <p><strong>Email:</strong> {{ users.user.email }}</p>
                    <p><strong>Адміністратор:</strong> {{ users.user.is_superuser }};</p>
                    <p><strong>Дата останього входу:</strong> {{ users.user.last_login }};</p>
                    <p><strong>Аватар:</strong> {{ users.avatar.url }}.</p>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

mysite/loginsys/templates/user_login.html
{% load staticfiles %} {% load i18n %}


<div class="row">
    {% if user.is_authenticated %}
        <div class="col-lg-3 col-xs-6 pull-right">
            <h4><a href="{% url 'loginsys:logout' %}">Вийти ({{ user.username }}) </a></h4>
        </div>
        <div class="col-lg-3 col-xs-6 pull-right">
            <h4><a href="{% url 'loginsys:update' %}">Змінити профіль</a></h4>
        </div>
    {% else %}
        <div class="col-lg-1 pull-right">
            <h4><a href="{% url 'loginsys:login' %}">{% trans 'Увійти' %}</a></h4>
        </div>
        <div class="col-lg-2 pull-right">
            <h4><a href="{% url 'loginsys:register' %}">{% trans 'Реєстрація' %}</a></h4>
        </div>
    {% endif %}
</div>


<div id="login" hidden="hidden" title="Вхід на сайт">
    <div id="login-register">
        <form action="" method="post">
            {% csrf_token %}
            <label for="username">І'мя користувача</label>
            <input  value="{{username}}" type="text" class="form-control" name="username"
                    id="username" placeholder="введіть ім'я користувача" >
            <div class="form-group has-error">
                {% if login_error_username %}
                    <label class="control-label errorlist"><em>{{login_error_username}}</em></label>
                {% endif %}
            </div>
            <label for="password">Пароль</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="пароль">
            <div class="form-group has-error">
                {% if login_error_password %}
                    <label class="control-label"><em>{{login_error_password}}</em></label>
                {% endif %}
            </div>
            <div class="form-group has-error">
                {% if login_error_username_password %}
                    <label class="control-label"><em>{{login_error_username_password}}</em></label>
                {% elif login_error%}
                    <label class="control-label"><em>{{login_error}}</em></label>
                {% endif %}
            </div>
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">{% trans 'Увійти' %}</button>
                <button id="cancel" type="button" class="btn btn-default pull-right">Відміна</button>
                <button type="button" class="btn btn-default"><a href="{% url 'loginsys:password_reset' %}">{% trans 'Забули пароль?' %}</a></button>
            </div>
        </form>
    </div>
</div>