mysite/blog/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url, include
from django.views.generic import TemplateView
from blog.views import (start_page,
                        article_list,
                        articles_list_update,
                        article_create,
                        article_update,
                        article_delete,
                        article_detail,
                        add_like,
                        photo)


app_name = 'blog'


urlpatterns = [
    # url(r'^mine/$', MyView.as_view(), name='my-view'),

    # include urls_api
    url(r'^api/', include('blog.class_based.urls')),

    url(r'^$', start_page, name='start_page'),

    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/list/$', article_list, name='article_list'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/list/update/$', articles_list_update,
        name='articles_list_update'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/create/$', article_create, name='article_create'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/edit/$', article_update,
        name='article_update'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/delete/$', article_delete,
        name='article_delete'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/$', article_detail,
        name='article_detail'),
    url(r'^(?P<item_slug>.*)/list/$', photo, name='photo'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact_page.html')),
    url(r'^add_like/(?P<id>[0-9]+)/$', add_like, name='add_like'),
    ]

mysite/languages/urls.py
from django.conf.urls import url
from languages.views import set_language


urlpatterns = [
    url(r'^(?P<lang_code>.*)/$', set_language, name='set_language'),
    ]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from admin.my_admin import misha


# urlpatterns = i18n_patterns(
#     url(r'^admin/', include(admin.site.urls)),
#     url(r'^', include('navigation.urls')),
#     url(r'^profile/', include('profiles.urls')),
# )

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^misha/', include(misha.urls)),                # My admin

    url(r'auth/', include('loginsys.urls', namespace='loginsys')),
    url(r'^', include('blog.urls', namespace='blog')),
    url(r'language/', include('languages.urls', namespace='language')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/languages/models.py
from django.db import models

# Create your models here.

mysite/languages/views.py
from django.shortcuts import redirect
from django.utils.translation import (
    LANGUAGE_SESSION_KEY, check_for_language, get_language, to_locale,)


def set_language(request, lang_code):

        path = request.META.get('HTTP_REFERER', '/')
        if lang_code and check_for_language(lang_code):
            if hasattr(request, 'session'):
                request.session[LANGUAGE_SESSION_KEY] = lang_code
                return redirect(path)
        # user_language = lang_code
        # translation.activate(user_language)
        # request.session[translation.LANGUAGE_SESSION_KEY] = user_language
        # return redirect(path)

mysite/languages/templates/languages/languages.html
{% load staticfiles %} {% load i18n %}


<!-- Languages -->
<div class="col-lg-3 pull-right">
    <ul>
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <li class="flag"><a href="{% url 'language:set_language' lang_code=language.code %}" title="{{ language.name_local }}">
                <img class="{% if LANGUAGE_CODE == language.code %} active-language {% else %} img-responsive{% endif %}"
                        {% if language.code == 'uk' %} src="{% static 'img/ukraine.jpg' %}" alt="Ukraine"
                        {% elif language.code == 'ru' %} src="{% static 'img/russia.jpeg' %}" alt="Russia"
                        {% elif language.code == 'en' %} src="{% static 'img/england.jpg' %}" alt="England"
                        {% endif %}/></a></li>
        {% endfor %}
    </ul>
</div>