mysite/blog/class_based/urls.py
from django.conf.urls import url, include
from blog.class_based.views import ArticleList, ArticleDetail, ArticleCreate, ArticleUpdate, ArticleDelete

app_name = 'api'

urlpatterns = [
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/create/$', ArticleCreate.as_view(), name='article_create'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/edit/$', ArticleUpdate.as_view(),
        name='article_update'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/delete/$', ArticleDelete.as_view(),
        name='article_delete'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/list/$', ArticleList.as_view(), name='article_list'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/$', ArticleDetail.as_view(),
        name='article_detail'),





    # url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/delete/$', 'blog.views.article_delete',
    #     name='article_delete'),
    # url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/$', 'blog.views.article_detail',
    #     name='article_detail')
]

mysite/blog/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url, include
from django.views.generic import TemplateView
from blog.views import (start_page,
                        article_list,
                        articles_list_update,
                        article_create,
                        article_update,
                        article_delete,
                        article_detail,
                        add_like,
                        photo)


app_name = 'blog'


urlpatterns = [
    # url(r'^mine/$', MyView.as_view(), name='my-view'),

    # include urls_api
    url(r'^api/', include('blog.class_based.urls')),

    url(r'^$', start_page, name='start_page'),

    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/list/$', article_list, name='article_list'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/list/update/$', articles_list_update,
        name='articles_list_update'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/create/$', article_create, name='article_create'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/edit/$', article_update,
        name='article_update'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/delete/$', article_delete,
        name='article_delete'),
    url(r'^(?P<item_slug>.*)/(?P<category_slug>.*)/(?P<article_slug>.*)/$', article_detail,
        name='article_detail'),
    url(r'^(?P<item_slug>.*)/list/$', photo, name='photo'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact_page.html')),
    url(r'^add_like/(?P<id>[0-9]+)/$', add_like, name='add_like'),
    ]

mysite/blog/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from loginsys.models import Profile
from navigation.models import Category
from django.utils.translation import ugettext_lazy as _
import os


def upload_location(instance, filename):
    path = 'upload/article_images'
    if instance.id is not None:
        return os.path.join(path, str(instance.id), str(filename))
    article = Article.objects.order_by("id").last()
    if not article:
        return os.path.join(path, 'FIRST_article', str(filename))
    if article.id is not None:
        new_id = article.id + 1
        return os.path.join(path, str(new_id), str(filename))


class Tag(models.Model):
    tag_title = models.CharField(max_length=50, verbose_name=_('Назва тега'))
    tag_name = models.SlugField(verbose_name=_('Ім`я тега транслітом'))

    class Meta:
        db_table = "tags"
        verbose_name = _("Тег")
        verbose_name_plural = _("Тегі")

    def __str__(self):
        return self.tag_title


class ArticleManager(models.Manager):
    def get_by_natural_key(self, article_title):
        return self.get(article_title=article_title)


class Article(models.Model):
    objects = ArticleManager()

    article_user = models.ForeignKey(Profile, related_name="articles", verbose_name=_("Автор статті"))
    article_title = models.CharField(max_length=50, verbose_name=_("Назва статті"), unique=True)
    article_text = models.TextField(max_length=1000, verbose_name=_("Текст статті"))
    article_category = models.ForeignKey(Category, related_name="articles", verbose_name=_("Категорія"),
                                         on_delete=models.CASCADE)
    article_tag = models.ManyToManyField(Tag, related_name="articles", verbose_name=_("Тегі"))
    article_date = models.DateTimeField(auto_now_add=True, verbose_name=_("Дата створення"))
    article_update = models.DateTimeField(auto_now=True, verbose_name=_("Дата оновлення"))
    article_likes = models.IntegerField(verbose_name=_("Подобається"), default=0)
    article_image = models.ImageField(verbose_name=_("Картинки"), upload_to=upload_location, blank=True, null=True,
                                      help_text=_("Зображення до статті"))
    article_slug = models.SlugField(verbose_name=_("Ім`я статті транслітом"), blank=True, unique=True)

    class Meta:
        db_table = "articles"
        verbose_name = _("Стаття")
        verbose_name_plural = _("Статті")

    def __str__(self):
        return self.article_title

    def natural_key(self):
        return self.article_title

    def get_image(self):
        if not self.article_image:
            return False
        else:
            return True

    def get_absolute_url(self):
        return reverse('blog:article_detail', kwargs={'item_slug': self.article_category.menu_category.menu_name,
                                                      'category_slug': self.article_category.category_name,
                                                      'article_slug': self.article_slug})
    get_absolute_url.admin_order_field = 'article_date'
    get_absolute_url.short_description = _('Абсолютна адреса')

mysite/blog/class_based/views.py
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from blog.models import Article
from comment.models import Comments
from navigation.models import Category, MenuItem
from blog.form import SendMassageForm, ArticleForm
from comment.forms import CommentForm
from django.core.exceptions import ObjectDoesNotExist
from django.http.response import HttpResponse, Http404, HttpResponseRedirect
from django.core.mail import send_mail
from django.conf import settings
from django.utils.translation import gettext as _
from loginsys.models import Profile
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.forms.models import modelformset_factory, inlineformset_factory
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormMixin, FormView


# articles list in class

class ArticleList(ListView):
    # model = Article
    # queryset = Article.objects.order_by('-article_date')
    template_name = 'gallery_works_api.html'
    context_object_name = 'articles'

    def get_queryset(self):
        self.category = get_object_or_404(Category, menu_category__menu_name=self.kwargs['item_slug'],
                                          category_name=self.kwargs['category_slug'])
        articles_list = Article.objects.filter(article_category=self.category).order_by('-article_date')
        query = self.request.GET.get('q')
        if query:
            articles_list = Article.objects.filter(
                Q(article_title__icontains=query) |
                Q(article_text__icontains=query)).distinct()
            return articles_list
        return articles_list

    def get_context_data(self, **kwargs):
        context = super(ArticleList, self).get_context_data(**kwargs)
        context['category'] = self.category
        context['articles_carousel'] = self.category.articles.all().order_by('-article_likes')[0:3]
        return context


# class ArticleCommentForm(View):
#     model = Comments
#     form_class = CommentForm
#     context_object_name = 'comments'
#
#     def get(self, request, *args, **kwargs):
#         form = self.form_class()
#         return render(request, self.template_name, {'form': form})
#
#     def post(self, request, *args, **kwargs):
#         form = self.form_class(request.POST)
#         if form.is_valid():
#
#             return HttpResponseRedirect(self.article.get_absolute_url())
#         return render(request, self.template_name, {'form': form})


class ArticleDetail(SingleObjectMixin, FormView):
    model = Article
    template_name = 'gallery_work_api.html'
    context_object_name = 'comments'
    slug_field = 'article_slug'
    slug_url_kwarg = 'article_slug'
    form_class = CommentForm
    paginate_by = 3

    def get_success_url(self):
        return reverse('blog:api:article_detail', kwargs={'item_slug': self.kwargs['item_slug'],
                                                          'category_slug': self.kwargs['category_slug'],
                                                          'article_slug': self.kwargs['article_slug']})

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Article.objects.all())
        return super(ArticleDetail, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ArticleDetail, self).get_context_data(**kwargs)
        form_class = self.get_form_class()
        comments_list = self.object.comments.all().order_by('-comments_create')
        current_page = Paginator(comments_list, self.paginate_by)
        page_number = self.request.GET.get('page', 1)
        context['form'] = self.get_form(form_class)
        context['article'] = self.object
        context['comments'] = current_page.page(page_number)
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            raise Http404(_('Ви немаєте прав для запису коментарів!'))
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if 'pause' in self.request.session:
            messages.error(self.request, _('Ви вже залишили коментар, зачекайте хвилину.'), extra_tags='error')
            return self.form_invalid(form)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        if not self.request.user.is_staff or not self.request.user.is_authenticated:
            raise Http404(_('Ви немаєте прав для створення статті!'))
        else:
            form.instance.comments_article = self.object
            form.instance.comments_user = get_object_or_404(Profile, user=self.request.user)
            form.save()
            self.request.session.set_expiry(60)
            self.request.session['pause'] = True
            messages.success(self.request, _('Коментар добавлений успішно!'), extra_tags='success')
            return super(ArticleDetail, self).form_valid(form)

# class ArticleDetail(SingleObjectMixin, ListView):
#     template_name = 'gallery_work_api.html'
#     # context_object_name = 'comments'
#     slug_field = 'article_slug'
#     slug_url_kwarg = 'article_slug'
#     form_class = CommentForm
#     paginate_by = 2
#
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object(queryset=Article.objects.all())
#         return super(ArticleDetail, self).get(request, *args, **kwargs)
#
#     def post(self, request, *args, **kwargs):
#         if not request.user.is_authenticated():
#             raise Http404(_('Ви немаєте прав для запису коментарів!'))
#         form = self.form_class(request.POST)
#         if form.is_valid():
#             return HttpResponseRedirect(self.object.get_absolute_url())
#         else:
#             return render(request, self.template_name, self.get_context_data())
#
#     def form_valid(self, form):
#         if not self.request.user.is_staff or not self.request.user.is_authenticated:
#             raise Http404(_('Ви немаєте прав для створення статті!'))
#         if 'pause' in self.request.session:
#             messages.error(self.request, _('Ви вже залишили коментар, зачекайте хвилину.'), extra_tags='error')
#         else:
#             form.instance.comments_article = self.object
#             form.instance.comments_user = get_object_or_404(Profile, user=self.request.user)
#             self.request.session.set_expiry(60)
#             self.request.session['pause'] = True
#             messages.success(self.request, _('Коментар добавлений успішно!'), extra_tags='success')
#             return super(ArticleCreate, self).form_valid(form)
#
#     def get_context_data(self, **kwargs):
#         context = super(ArticleDetail, self).get_context_data(**kwargs)
#         context['form'] = self.form_class
#         context['article'] = self.object
#         return context
#
#     def get_queryset(self):
#         return self.object.comments.all()


# class ArticleDetail(DetailView):
#     model = Comments
#     template_name = 'gallery_work_api.html'
#     context_object_name = 'comments'
#     slug_field = 'article_slug'
#     slug_url_kwarg = 'article_slug'
#
#     def get_queryset(self):
#         self.article = get_object_or_404(Article, article_category__menu_category__menu_name=self.kwargs['item_slug'],
#                                          article_category__category_name=self.kwargs['category_slug'],
#                                          article_slug=self.kwargs['article_slug'])
#         return Comments.objects.filter(comments_article=self.article).order_by('-comments_create')
#
#     def get_context_data(self, **kwargs):
#         context = super(ArticleCommentDetail, self).get_context_data(**kwargs)
#         context['form'] = CommentForm()
#         context['article'] = self.article
#         return context


def user_is_superuser(cl):
    """
    It`s my own decorator which check user. User must be superuser
    """
    def inner(request, *args, **kwargs):
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404(_('Ви немаєте прав для створення статті!'))
        else:
            return cl(request, *args, **kwargs)
    return inner


class ArticleCreate(CreateView):
    model = Article
    template_name = 'article_form_api.html'
    form_class = ArticleForm

    @method_decorator(user_is_superuser)
    def dispatch(self, *args, **kwargs):
        return super(ArticleCreate, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        if not self.request.user.is_staff or not self.request.user.is_superuser:
            raise Http404(_('Ви немаєте прав для створення статті!'))
        else:
            form.instance.article_user = get_object_or_404(Profile, user=self.request.user)
            return super(ArticleCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ArticleCreate, self).get_context_data(**kwargs)
        context['title'] = _('Форма для створення статті')
        context['button_create'] = _('створити статтю')
        context['button_cancel'] = _('відміна')
        context['return_path'] = get_object_or_404(Category,  menu_category__menu_name=self.kwargs['item_slug'],
                                                   category_name=self.kwargs['category_slug']).get_absolute_url()
        return context


class ArticleUpdate(UpdateView):
    model = Article
    template_name = 'article_form_api.html'
    form_class = ArticleForm

mysite/blog/templates/blog/article_delete_form.html
{% extends "base.html" %} {% load staticfiles %} {% load i18n %}


{% block title%}{{title}}{% endblock title%}

{% block style %}

{% endblock style %}

{% block create_article_form %}

<div class="col-sm-3 col-sm-offset-4">
    <h4 class="danger">{{title}}</h4>
    <form  method="POST" action="">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="{{button_delete}}"/>
        <a class="btn btn-default pull-right" href="{{ return_path }}">{{ button_cancel }}</a>
    </form>
</div>

{% endblock create_article_form %}

mysite/blog/templates/blog/article_form.html
{% extends 'base.html' %}

{% block title%}{{title}}{% endblock title%}

{% block style %}

{% endblock style %}

{% block create_article_form %}

    <div class="col-sm-4 col-sm-offset-4">
        <h2>{{title}}</h2>
        <form  method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input class="btn btn-primary" type="submit" value="{{button_create}}"/>
            <button type="button" class="btn btn-default pull-right"><a href="{{ return_path }}">{{ button_cancel }}</a></button>
        </form>
    </div>

{% endblock create_article_form %}

mysite/blog/templates/blog/articles_list_update.html
{% extends 'base.html' %}

{% block title%}{{title}}{% endblock title%}

{% block style %}

{% endblock style %}

{% block create_article_form %}

    <div class="col-sm-4 col-sm-offset-4">
        <h2>{{title}}</h2>
        <form  method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{forms.as_p}}
            <input class="btn btn-primary" type="submit" value="{{button_create}}"/>
            <button type="button" class="btn btn-default pull-right"><a href="{{ return_path }}">{{ button_cancel }}</a></button>
        </form>
    </div>

{% endblock create_article_form %}

mysite/blog/templates/blog/gallery_work.html
{% extends "base.html" %} {% load staticfiles %} {% load i18n %}


{% block title %}3D MAX | {{ article.article_title|capfirst }}{% endblock %}


{% block style %}

{% endblock %}


{% block content %}

    {% if user.is_superuser %}
        <div class="row">
            <div class="col-md-3">
                <a class="create_update"
                   href="{% url 'blog:article_update' item_slug=article.article_category.menu_category.menu_name category_slug=article.article_category.category_name article_slug=article.article_slug %}"><h3>{% trans 'Змінити статтю?' %}</h3></a>
            </div>
            <div class="col-md-3 pull-right">
                <a class="create_update" href="{% url 'blog:article_delete' item_slug=article.article_category.menu_category.menu_name category_slug=article.article_category.category_name article_slug=article.article_slug %}"><h3>{% trans 'Видалити статтю?' %}</h3></a>
            </div>
        </div>
    {% endif %}

    <!-- gallery_work -->
    <div id="work_3d_max">
        {% if article.article_image %}
            <img class="img-responsive img-thumbnail" src="{{article.article_image.url}}" alt="{{ article.article_title }}"/>
        {% endif %}
        <div class="image_title article">
            <ul class="likes">
                <li>
                    <a href="{% url 'blog:add_like' article.id %}"><img src="{% static 'blog/img/like.png' %}"></a>
                </li>
                <li>
                    <h5>{{ article.article_likes }}</h5>
                </li>
            </ul>
        </div>
        <h4>{{ article.article_title }}</h4>
    </div>
    <div class="well">
        <p>{{ article.article_text }}</p>
    </div>
    {% if comments %}
        <div class="col-lg-7 col-md-7 col-sm-9 well">
            <div class="col-md-offset-1">
                <h4><strong>Коментарі:</strong></h4>
            </div>
            <hr>
            {% for comment in comments %}
                <p>{{comment.comments_text}}</p>
                <img class="img-responsive ava" src="{{ comment.comments_user.avatar.url }}"
                     alt="{{comment.comments_user.username}}">
                <p><strong>{{comment.comments_user.user.username}}</strong> <em>{{comment.comments_create}}</em></p>
                <hr>
            {% endfor %}
        </div>
    {% endif %}
    {% if user.is_authenticated %}
        <div class="col-lg-6 col-md-6 col-sm-8 article well">
            {% comment %} <form id="form-massage" class="form-row" action="{% url 'gallery_work' article.id %}" method="POST">
                <fieldset>
                    <div class="form-group">
                        {% csrf_token %}
                        {% for field in form %}
                            {{ field.label_tag }}
                            {{ field.errors }}
                            {{ field }}
                            {{ field.help_text }}
                            </div>
                        {% endfor %}
                    <button type="submit" class="btn btn-primary">добавити коментар</button>
                </fieldset>
            </form>{% endcomment %}

            <form id="form-massage" class="form-row" action="" method="POST">
                <fieldset>
                    <div class="form-group">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit" class="btn btn-primary">добавити коментар</button>
                    </div>
                </fieldset>
            </form>


            {% comment %} <form id="form-massage" class="form-row" action="{% url 'gallery_work' article.id %}" method="POST">
            <fieldset>
                <div class="form-group">
                    <label for="{{ form.comments_text.id_for_label }}" class="control-label">{{ form.comments_text.label }}</label>
                    {{ label_tag }}
                    <div class="col-lg-12">
                        {% csrf_token %}
                        {{ form.comments_text.errors }}
                        {{ form.comments_text }}
                         <button type="submit" class="btn btn-primary">добавити коментар</button>
                    </div>
                </div>
            </fieldset>
        </form>{% endcomment %}
        </div>

    {% endif %}
    {#    <div id="pagination" class="row">#}
    {#        <ul class="pagination">#}
    {#            {% if comments.has_other_pages %}#}
    {#                {% if comments.has_previous %}#}
    {#                    <li><a href="?page={{ comments.previous_page_number }}">&laquo;</a></li>#}
    {#                {% else %}#}
    {#                    <li class="disabled"><a href="">&laquo;</a></li>#}
    {#                {% endif %}#}
    {#                {% for page in comments.paginator.page_range %}#}
    {#                    {% if page == comments.number %}#}
    {#                        <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>#}
    {#                    {% else %}#}
    {#                        <li><a href="?page={{ page }}">{{ page }}</a></li>#}
    {#                    {% endif%}#}
    {#                {% endfor %}#}
    {#                {% if comments.has_next %}#}
    {#                    <li><a href="?page={{ comments.next_page_number }}">&raquo</a></li>#}
    {#                {% else %}#}
    {#                    <li class="disabled"><a href="">&raquo</a></li>#}
    {#                {% endif %}#}
    {#            {% endif %}#}
    {#        </ul>#}
    {#    </div>#}
    {% if comments.has_other_pages %}
        <div id="pagination" class="col-lg-10  col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
            <ul class="pager">
                {% if comments.has_previous %}
                    <li class="previous"><a href="?page={{ comments.previous_page_number }}">← Новіші коментарі</a></li>
                {% else %}
                    <li class="previous disabled"><a href="">← Новіші коментарі</a></li>
                {% endif %}
                {% if comments.has_next %}
                    <li class="next"><a href="?page={{ comments.next_page_number }}">Старіші коментарі →</a></li>
                {% else %}
                    <li class="next disabled"><a href="">Старіші коментарі →</a></li>
                {% endif %}
                <style>
                    .article.well {
                        margin-bottom: 10px;
                    }
                </style>
            </ul>
        </div>
    {% endif %}

{% endblock %}

mysite/blog/templates/blog/gallery_works.html
{% extends "base.html" %} {% load staticfiles %} {% load my_filters %} {% load i18n %} {% load humanize %}


{% block title %}3D MAX | {{ category.category_title }} {% endblock %}


{% block style %}

    <style>
        html, body {
            background-image: url("/static/img/3.jpg");
        }
    </style>

{% endblock %}


{% block content %}

    {% if user.is_superuser %}
        <div class="row">
            <div class="col-md-4">
                <a class="create_update" href="{% url 'blog:articles_list_update' item_slug=category.menu_category.menu_name category_slug=category.category_name %}"><h3>{% trans 'Змінити список статей?' %}</h3></a>
            </div>
            <div class="col-md-4 pull-right">
                <a class="create_update" href="{% url 'blog:article_create' item_slug=category.menu_category.menu_name category_slug=category.category_name %}"><h3>{% trans 'Створити нову статтю?' %}</h3></a>
            </div>
        </div>
    {% endif %}

    <!-- Carousel -->
        {% if articles_carousel %}
        <div id="myCarousel" class="carousel slide" data-ride="carousel">

            <!-- Indicators -->
            {% if articles_carousel.count > 1 %}
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    {% if articles_carousel.count == 2 %}
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                    {% else %}
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                    {% endif %}
                </ol>
            {% endif %}
            <div class="carousel-inner" role="listbox">
                {% for article_carousel in articles_carousel %}
                    <div class="{% if article_carousel != articles_carousel.0 %} item {% else %} item active {% endif %}">
                        <img class="first-slide" src="{{ article_carousel.article_image.url }}" alt="{{ article_carousel.article_title }}">
                        <div class="container">
                            <div class="carousel-caption">
                                <h1>{{ article_carousel.article_title }}</h1>
                                <p>{{ article_carousel.article_text|shot_text:200|capfirst }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% if articles_carousel.count > 1 %}
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            {% endif %}
        </div>

        <!-- search_works -->
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <form class="form-group input-group" method="get" action="">
                    <input class="form-control" type="text" name="q" placeholder="пошук статті" value="{{ request.GET.q }}"/>
                    <span class="input-group-btn">
                        <input class="btn btn-primary" type="submit" value="Пошук"/>
                    </span>
                </form>
            </div>
        </div>

    {% else %}

        <div class="col-md-10 col-md-offset-2">
            <h2>Даний список покищо пустий!</h2>
        </div>

    {% endif %}

    <!-- gallery_works -->
    <div id="works_3d_max">
        {% for article in articles %}
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">

                {% if article.article_image %}
                    <div class="d3_image">
                        <a href="{{ article.get_absolute_url }}" title="{{ article.article_title }}"><img class="img-responsive img-rounded" src="{{article.article_image.url}}" alt="{{ article.article_title }}"/></a>
                    </div>
                {% endif %}
                <div class="image_title">
                    <ul>
                        <li>
                            <ul class="likes">
                                <li><a href="{% url 'blog:add_like' article.id %}"><img src="{% static 'blog/img/like.png' %}"></a></li>
                                <li> <h5>{{ article.article_likes }}</h5></li>
                                <li style="float: right"><h5>Створена: {{ article.article_date|naturaltime }}</h5></li>
                            </ul>
                        </li>
                        <li><a href="{{ article.get_absolute_url }}"><h4>{{ article.article_title }}</h4></a></li>
                    </ul>
                </div>
            </div>
        {% endfor %}
    </div>

    {% if articles.has_other_pages %}

        <div id="pagination" class="row">
            <ul class="pagination">
                {% if articles.has_previous %}
                    <li><a href="?page={{ articles.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><a href="">&laquo;</a></li>
                {% endif %}
                {% for page in list_pagination %}
                    {% if page == articles.number %}
                        <li class="active"><a href="?page={{ page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ page }}</a></li>
                    {% elif page == page_before or page == page_after %}
                        <li><a href="">...</a></li>
                    {% else %}
                        <li><a href="?page={{ page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ page }}</a></li>
                    {% endif%}
                {% endfor %}
                {% if articles.has_next %}
                    <li><a href="?page={{ articles.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&raquo</a></li>
                {% else %}
                    <li class="disabled"><a href="">&raquo</a></li>
                {% endif %}
            </ul>
        </div>

    {% endif %}

{% endblock %}

mysite/blog/templates/blog/photo_list.html
{% extends "base.html" %} {% load staticfiles %} {% load my_filters %} {% load i18n %}


{% block title %}{{ menu_item.menu_title }} {% endblock %}


{% block style %}

    <style>
        html, body {
            background-image: url("/static/img/2.jpg");
        }
    </style>

{% endblock %}


{% block content %}

    {% if user.is_superuser %}
        <div class="row">
            <div class="col-md-4">
                <a class="create_update" href="{% url 'blog:article_create' item_slug=category.menu_category.menu_name category_slug=category.category_name %}"><h3>{% trans 'Створити нову статтю?' %}</h3></a>
            </div>
        </div>
    {% endif %}
{% endblock %}